[package]
name = "art"
version = "0.1.0"
edition = "2021"
description = "A llibrary for modeling artistic cpncepts"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
