[package]
name = "adder"
version = "0.1.0"
authors = ["Michael CHLON <mic.a.elle.chlon@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
add-one = { path = "../add-one" }
rand = "0.8.3"
